### ISSUE TITLE
Error with 24px

### ISSUE THREAD

**Issue by maxime98** [jdhxyy/ssd1306py-micropython#5]
Hi, I've got an error with ascii24.py (Note that work great with ascii16.py with modify 86 to 85)

>>> %Run -c $EDITOR_CONTENT
Scan i2c bus...
/lib/ssd1306py/ascii24.txt
00
0x00
0x00
0x00
0x80
0x00
0x00
0x00
#f
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/lib/ssd1306py/ops.py", line 73, in text
  File "/lib/ssd1306py/ascii24.py", line 43, in display
  File "/lib/ssd1306py/ascii24.py", line 26, in _get_ch
ValueError: invalid syntax for integer with base 10
>>>

**Comment by treysis** [comment]
Change 249 to 247?
