### ISSUE TITLE
OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by woodgreat** [jdhxyy/ssd1306py-micropython#6]
in main.py
...

line 16>  lcd.text('font16x16', 0, 4, 16)
...

----------------------------------------------

MPY: soft reboot
Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/lib/ssd1306py/ops.py", line 66, in text
  File "/lib/ssd1306py/ascii16.py", line 36, in display
  File "/lib/ssd1306py/ascii16.py", line 15, in _get_ch
OSError: [Errno 2] ENOENT

--------------------------------------------
I checked  ascii16.py

---------------
        _file = open(sys.path[1] + '/ssd1306py/ascii16.txt', 'r')
---------------

why error came?

**Comment by treysis** [comment]
Try to change to:
`_file = open('/ssd1306py/ascii16.txt', 'r')`

**Comment by sarakii** [comment]
> Try to change to: `_file = open('/ssd1306py/ascii16.txt', 'r')`

it works when i try :
`_file = open('/lib/ssd1306py/ascii16.txt', 'r')`

**Comment by treysis** [comment]
True. Depends on where you put your folder. But this font is very slow. Better to use another one.

**Comment by letr007** [comment]
> in main.py ...
> 
> line 16> lcd.text('font16x16', 0, 4, 16) ...
> 
> MPY: soft reboot Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead Traceback (most recent call last): File "", line 16, in File "/lib/ssd1306py/ops.py", line 66, in text File "/lib/ssd1306py/ascii16.py", line 36, in display File "/lib/ssd1306py/ascii16.py", line 15, in _get_ch OSError: [Errno 2] ENOENT
> 
> I checked ascii16.py
> 
> ```
>     _file = open(sys.path[1] + '/ssd1306py/ascii16.txt', 'r')
> ```
> 
> why error came?

You can also change it to sys.path[2], which would also make it work
